name: Build LIME2 Kernel
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Show tcon0 quirks
        run: |
          grep -A8 "sun7i_a20_tcon0_quirks" $(find . -path "*/sun4i/sun4i_tcon.c" | head -1)
